// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;

	public delegate void ChangeSizeHandler(object o, ChangeSizeArgs args);

	public class ChangeSizeArgs : GLib.SignalArgs {
		public uint Size{
			get {
				return (uint) Args[0];
			}
		}

	}
}
