// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;

	public delegate void ChangeBackgroundHandler(object o, ChangeBackgroundArgs args);

	public class ChangeBackgroundArgs : GLib.SignalArgs {
		public Gnome.PanelAppletBackgroundType Type{
			get {
				return (Gnome.PanelAppletBackgroundType) Args[0];
			}
		}

		public Gdk.Color Color{
			get {
				return (Gdk.Color) Args[1];
			}
		}

		public Gdk.Pixmap Pixmap{
			get {
				return (Gdk.Pixmap) Args[2];
			}
		}

	}
}
