// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;

	public delegate void MoveFocusOutOfAppletHandler(object o, MoveFocusOutOfAppletArgs args);

	public class MoveFocusOutOfAppletArgs : GLib.SignalArgs {
		public Gtk.DirectionType Direction{
			get {
				return (Gtk.DirectionType) Args[0];
			}
		}

	}
}
