// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _GtkSharp.GnomeSharp {

	public class ObjectManager {

		static bool initialized = false;
		// Call this method from the appropriate module init function.
		public static void Initialize ()
		{
			if (initialized)
				return;

			initialized = true;
			GLib.GType.Register (_Gnome.PanelApplet.GType, typeof (_Gnome.PanelApplet));
		}
	}
}
