// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;
	using System.Runtime.InteropServices;

	#region Autogenerated code
	public enum PanelAppletBackgroundType {

		NoBackground,
		ColorBackground,
		PixmapBackground,
	}
	#endregion
}
