// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;
	using System.Runtime.InteropServices;

	#region Autogenerated code
	[Flags]
	public enum PanelAppletFlags {

		FlagsNone,
		ExpandMajor = 1 << 0,
		ExpandMinor = 1 << 1,
		HasHandle = 1 << 2,
	}
	#endregion
}
