// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace _Gnome {

	using System;

	public delegate bool PanelAppletFactoryCallback(_Gnome.PanelApplet applet, string iid);

}
