.TH TOMBOY 1 "October 14, 2004" gnome "GNOME User's Manuals"
.\" NAME should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)

.SH NAME
tomboy \- A simple note-taking application for Gnome

.SH SYNOPSIS
.B tomboy
.I "[OPTION] ..."

.SH "DESCRIPTION"
This manual page documents briefly the
.BR tomboy
command.
.\"Instead, it has documentation in the GNU Info format; see below.
.PP
.B Tomboy
is a desktop note-taking application for Linux and Unix. Simple and
easy to use, but with potential to help you organize the ideas and
information you deal with every day.
.PP
Tomboy's usefulness lies in the ability to relate notes and ideas
together, using a WikiWiki-like linking system.
.PP
When run without any options, the Tomboy note menu appears in the
Gnome Panel's notification tray area.  Selecting a note from the menu
displays the note's spatial window.
.PP
Changes to notes are saved automatically.  Links to URLs, files, and
other notes are detected as you type.  Rich editing such as
highlighting, bold, italics, undo/redo, and variable font sizes are
supported.
.PP
Global keybindings exist to allow fast access to Tomboy notes and
dialogs.  These keybindings are set in GConf (see below) and may be
activated from any application.

.SH OPTIONS
The program follows the usual GNU command line syntax, with
options starting with two dashes (`--').
A summary of options are included below.
.\"For a complete description, see the Info files.
.TP
.B \-\-new-note
Create and display a new note.
.TP
.B \-\-new-note TITLE
Create and display a new note with the title given.
.TP
.B \-\-open-note TITLE/URL
Display the existing note matching TITLE or URL.
.TP
.B \-\-note-path [PATH]
Load/store note data in this directory.
.TP
.B \-\-start-here
Display the "Start Here" note.
.TP
.B \-\-panel-applet
Launches Tomboy as a panel applet. This feature is not meant for users, but must be utilized only by gnome-panel.
.TP
.B \-\-search TEXT
Searches notes for the specified TEXT and opens the Search All Notes window with the search text
.TP
.B \-\-highlight-search TEXT
Search and highlight TEXT in the opened note.
.TP
.B \-\-help	
Show summary of options.
.TP
.B \-\-version
Show version of program.
.TP
.B \-\-debug
Turn on debugging output.

.SH "GCONF SETTINGS"
Tomboy has several preference settings stored in GConf.  Changes to
Settings are applied instantly to any running Tomboy instance. A
summary of the GConf settings and their purpose are described below.
.TP
.B /apps/tomboy/global_keybindings/open_start_here
Global X keybinding for displaying the "Start Here" note.
The default keybinding is <Alt>F11.
.TP
.B /apps/tomboy/global_keybindings/show_note_menu
Global X keybinding for displaying the Tomboy applet's note menu.
The default keybinding is <Alt>F12.
.TP
.B /apps/tomboy/global_keybindings/create_new_note
Global X keybinding for creating and displaying a new note.
.TP
.B /apps/tomboy/global_keybindings/open_recent_changes
Global X keybinding for opening the recent changes dialog.
.TP
.B /apps/tomboy/global_keybindings/open_search
Global X keybinding for opening the note search dialog.

.SH "SEE ALSO"
.I http://www.beatniksoftware.com/tomboy/
.\"The program is documented fully by
.\".IR "The Rise and Fall of a Fooish Bar" ,
.\"available via the Info system.

.SH BUGS
Please send bug reports to the Tomboy mailing list
(tomboy-list@beatniksoftware.com) or enter them in the Gnome Bugzilla
bug tracker (http://bugzilla.gnome.org/enter_bug.cgi?product=Tomboy).

.SH AUTHOR
Alex Graveley <alex@beatniksoftware.com>

This manual page was originally written by Luca Capello <luca@pca.it>.
